import { Bike, Category } from "./common/types";

export const bikesList: Array<Bike> = [
  {
    id: "cano_one",
    name: "Cano One",
    category: Category.road,
    price: 2850,
    imgSrc: "im1-min.png",
    specifications: {
      batteryCapacity: "72V 50Ah",
      motorPower: "5000W",
      maxSpeed: "85 km/h",
      range: "200 km",
      weight: "45 kg",
      chargingTime: "4 hours",
    },
    sellers: [
      { name: "Amazon", price: 2850, url: "https://amazon.com" },
      { name: "eBay", price: 2900, url: "https://ebay.com" },
      { name: "Direct Store", price: 2799, url: "https://store.com" },
    ],
  },
  {
    id: "predator",
    name: "Predator",
    category: Category.bmx,
    price: 1620,
    imgSrc: "im12-min.png",
    specifications: {
      batteryCapacity: "60V 30Ah",
      motorPower: "3000W",
      maxSpeed: "70 km/h",
      range: "150 km",
      weight: "38 kg",
      chargingTime: "3.5 hours",
    },
    sellers: [
      { name: "Amazon", price: 1620, url: "https://amazon.com" },
      { name: "Walmart", price: 1650, url: "https://walmart.com" },
      { name: "Direct Store", price: 1599, url: "https://store.com" },
    ],
  },
  {
    id: "canyon",
    name: "Canyon",
    category: Category.mountain,
    price: 780,
    imgSrc: "im2-min.png",
    specifications: {
      batteryCapacity: "48V 20Ah",
      motorPower: "1500W",
      maxSpeed: "50 km/h",
      range: "80 km",
      weight: "28 kg",
      chargingTime: "2.5 hours",
    },
    sellers: [
      { name: "Amazon", price: 780, url: "https://amazon.com" },
      { name: "Best Buy", price: 799, url: "https://bestbuy.com" },
      { name: "Direct Store", price: 749, url: "https://store.com" },
    ],
  },
  {
    id: "coselo",
    name: "Coselo",
    category: Category.road,
    price: 1100,
    imgSrc: "im3-min.png",
    specifications: {
      batteryCapacity: "60V 25Ah",
      motorPower: "2000W",
      maxSpeed: "60 km/h",
      range: "120 km",
      weight: "32 kg",
      chargingTime: "3 hours",
    },
    sellers: [
      { name: "Amazon", price: 1100, url: "https://amazon.com" },
      { name: "eBay", price: 1120, url: "https://ebay.com" },
      { name: "Direct Store", price: 1079, url: "https://store.com" },
    ],
  },
  {
    id: "gt_cube",
    name: "Gt Cube",
    category: Category.mountain,
    price: 450,
    imgSrc: "im4-min.png",
    specifications: {
      batteryCapacity: "36V 15Ah",
      motorPower: "1000W",
      maxSpeed: "40 km/h",
      range: "60 km",
      weight: "22 kg",
      chargingTime: "2 hours",
    },
    sellers: [
      { name: "Amazon", price: 450, url: "https://amazon.com" },
      { name: "Walmart", price: 469, url: "https://walmart.com" },
      { name: "Direct Store", price: 439, url: "https://store.com" },
    ],
  },
  {
    id: "cube_axeal",
    name: "Cube Axeal",
    category: Category.road,
    price: 600,
    imgSrc: "im5-min.png",
    specifications: {
      batteryCapacity: "48V 18Ah",
      motorPower: "1200W",
      maxSpeed: "45 km/h",
      range: "90 km",
      weight: "25 kg",
      chargingTime: "2.5 hours",
    },
    sellers: [
      { name: "Amazon", price: 600, url: "https://amazon.com" },
      { name: "eBay", price: 615, url: "https://ebay.com" },
      { name: "Direct Store", price: 589, url: "https://store.com" },
    ],
  },
  {
    id: "gt_3000",
    name: "Gt 3000",
    category: Category.mountain,
    price: 320,
    imgSrc: "im7-min.png",
    specifications: {
      batteryCapacity: "36V 10Ah",
      motorPower: "750W",
      maxSpeed: "32 km/h",
      range: "50 km",
      weight: "20 kg",
      chargingTime: "1.5 hours",
    },
    sellers: [
      { name: "Amazon", price: 320, url: "https://amazon.com" },
      { name: "Walmart", price: 335, url: "https://walmart.com" },
      { name: "Direct Store", price: 309, url: "https://store.com" },
    ],
  },
  {
    id: "gt_one",
    name: "Gt One",
    category: Category.mountain,
    price: 500,
    imgSrc: "im8-min.png",
    specifications: {
      batteryCapacity: "48V 15Ah",
      motorPower: "1200W",
      maxSpeed: "48 km/h",
      range: "75 km",
      weight: "24 kg",
      chargingTime: "2 hours",
    },
    sellers: [
      { name: "Amazon", price: 500, url: "https://amazon.com" },
      { name: "Best Buy", price: 519, url: "https://bestbuy.com" },
      { name: "Direct Store", price: 489, url: "https://store.com" },
    ],
  },
  {
    id: "gt_performer",
    name: "Gt Perfomer",
    category: Category.bmx,
    price: 2200,
    imgSrc: "im9-min.png",
    specifications: {
      batteryCapacity: "72V 40Ah",
      motorPower: "4000W",
      maxSpeed: "80 km/h",
      range: "180 km",
      weight: "42 kg",
      chargingTime: "3.5 hours",
    },
    sellers: [
      { name: "Amazon", price: 2200, url: "https://amazon.com" },
      { name: "eBay", price: 2250, url: "https://ebay.com" },
      { name: "Direct Store", price: 2179, url: "https://store.com" },
    ],
  },
  {
    id: "haibike",
    name: "Haibike",
    category: Category.mountain,
    price: 1250,
    imgSrc: "im10-min.png",
    specifications: {
      batteryCapacity: "60V 35Ah",
      motorPower: "2500W",
      maxSpeed: "65 km/h",
      range: "140 km",
      weight: "36 kg",
      chargingTime: "3 hours",
    },
    sellers: [
      { name: "Amazon", price: 1250, url: "https://amazon.com" },
      { name: "Best Buy", price: 1279, url: "https://bestbuy.com" },
      { name: "Direct Store", price: 1229, url: "https://store.com" },
    ],
  },
  {
    id: "kenda_xl",
    name: "Kenda XL",
    category: Category.bmx,
    price: 1350,
    imgSrc: "im11-min.png",
    specifications: {
      batteryCapacity: "60V 28Ah",
      motorPower: "2800W",
      maxSpeed: "68 km/h",
      range: "160 km",
      weight: "40 kg",
      chargingTime: "3.2 hours",
    },
    sellers: [
      { name: "Amazon", price: 1350, url: "https://amazon.com" },
      { name: "eBay", price: 1375, url: "https://ebay.com" },
      { name: "Direct Store", price: 1329, url: "https://store.com" },
    ],
  },
  {
    id: "forme_long",
    name: "Forme Long",
    category: Category.road,
    price: 1900,
    imgSrc: "im6-min.png",
    specifications: {
      batteryCapacity: "72V 45Ah",
      motorPower: "3500W",
      maxSpeed: "75 km/h",
      range: "170 km",
      weight: "41 kg",
      chargingTime: "3.5 hours",
    },
    sellers: [
      { name: "Amazon", price: 1900, url: "https://amazon.com" },
      { name: "Walmart", price: 1929, url: "https://walmart.com" },
      { name: "Direct Store", price: 1879, url: "https://store.com" },
    ],
  },
];
